// Objective-C API for talking to github.com/status-im/go-waku/mobile Go package.
//   gobind -lang=objc github.com/status-im/go-waku/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Gowaku_H__
#define __Gowaku_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol GowakuSignalHandler;
@class GowakuSignalHandler;

@protocol GowakuSignalHandler <NSObject>
- (void)handleSignal:(NSString* _Nullable)p0;
@end

FOUNDATION_EXPORT NSString* _Nonnull GowakuAddPeer(NSString* _Nullable address, NSString* _Nullable protocolID);

FOUNDATION_EXPORT NSString* _Nonnull GowakuConnect(NSString* _Nullable address, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuConnectPeerID(NSString* _Nullable peerID, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuContentTopic(NSString* _Nullable applicationName, long applicationVersion, NSString* _Nullable contentTopicName, NSString* _Nullable encoding);

FOUNDATION_EXPORT NSString* _Nonnull GowakuDecodeAsymmetric(NSString* _Nullable messageJSON, NSString* _Nullable privateKey);

FOUNDATION_EXPORT NSString* _Nonnull GowakuDecodeSymmetric(NSString* _Nullable messageJSON, NSString* _Nullable symmetricKey);

FOUNDATION_EXPORT NSString* _Nonnull GowakuDefaultPubsubTopic(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuDisconnect(NSString* _Nullable peerID);

FOUNDATION_EXPORT NSString* _Nonnull GowakuLightpushPublish(NSString* _Nullable messageJSON, NSString* _Nullable topic, NSString* _Nullable peerID, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuLightpushPublishEncodeAsymmetric(NSString* _Nullable messageJSON, NSString* _Nullable topic, NSString* _Nullable peerID, NSString* _Nullable publicKey, NSString* _Nullable optionalSigningKey, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuLightpushPublishEncodeSymmetric(NSString* _Nullable messageJSON, NSString* _Nullable topic, NSString* _Nullable peerID, NSString* _Nullable symmetricKey, NSString* _Nullable optionalSigningKey, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuListenAddresses(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuNewNode(NSString* _Nullable configJSON);

FOUNDATION_EXPORT NSString* _Nonnull GowakuPeerCnt(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuPeerID(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuPeers(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuPubsubTopic(NSString* _Nullable name, NSString* _Nullable encoding);

FOUNDATION_EXPORT NSString* _Nonnull GowakuRelayEnoughPeers(NSString* _Nullable topic);

FOUNDATION_EXPORT NSString* _Nonnull GowakuRelayPublish(NSString* _Nullable messageJSON, NSString* _Nullable topic, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuRelayPublishEncodeAsymmetric(NSString* _Nullable messageJSON, NSString* _Nullable topic, NSString* _Nullable publicKey, NSString* _Nullable optionalSigningKey, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuRelayPublishEncodeSymmetric(NSString* _Nullable messageJSON, NSString* _Nullable topic, NSString* _Nullable symmetricKey, NSString* _Nullable optionalSigningKey, long ms);

FOUNDATION_EXPORT NSString* _Nonnull GowakuRelaySubscribe(NSString* _Nullable topic);

FOUNDATION_EXPORT NSString* _Nonnull GowakuRelayUnsubscribe(NSString* _Nullable topic);

// skipped function SetEventCallback with unsupported parameter or return types


/**
 * SetMobileSignalHandler setup geth callback to notify about new signal
used for gomobile builds
nolint
 */
FOUNDATION_EXPORT void GowakuSetMobileSignalHandler(id<GowakuSignalHandler> _Nullable handler);

FOUNDATION_EXPORT NSString* _Nonnull GowakuStart(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuStop(void);

FOUNDATION_EXPORT NSString* _Nonnull GowakuStoreQuery(NSString* _Nullable queryJSON, NSString* _Nullable peerID, long ms);

@class GowakuSignalHandler;

/**
 * SignalHandler defines a minimal interface
a signal handler needs to implement.
nolint
 */
@interface GowakuSignalHandler : NSObject <goSeqRefInterface, GowakuSignalHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)handleSignal:(NSString* _Nullable)p0;
@end

#endif
