
// Objective-C API for talking to the following Go packages
//
//	github.com/status-im/go-waku/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gowaku_FRAMEWORK_H__
#define __Gowaku_FRAMEWORK_H__

#include "Gowaku.objc.h"
#include "Universe.objc.h"

#endif
